### ISSUE TITLE
获取课程列表失败

### ISSUE THREAD

**Issue by loiang** [zzzz0317/umooc-video#1]
![Snipaste_2021-04-21_22-56-12](https://user-images.githubusercontent.com/59107199/115575997-ab539180-a2f5-11eb-9c7d-79fff2d74868.png)
https://umooc.gdgm.cn/meol
![Snipaste_2021-04-21_23-08-33](https://user-images.githubusercontent.com/59107199/115576996-9cb9aa00-a2f6-11eb-974d-474584cd3d93.png)
还更新吗

**Comment by userjust** [comment]
> ![Snipaste_2021-04-21_22-56-12](https://user-images.githubusercontent.com/59107199/115575997-ab539180-a2f5-11eb-9c7d-79fff2d74868.png)
> https://umooc.gdgm.cn/meol
> ![Snipaste_2021-04-21_23-08-33](https://user-images.githubusercontent.com/59107199/115576996-9cb9aa00-a2f6-11eb-974d-474584cd3d93.png)
> 还更新吗
